[Paths]
Prefix = /media/ssd/skyhammer/neue/install/aarch64-unknown-linux-gnu/miniforge3/envs/osl
Binaries = /media/ssd/skyhammer/neue/install/aarch64-unknown-linux-gnu/miniforge3/envs/osl/bin
Libraries = /media/ssd/skyhammer/neue/install/aarch64-unknown-linux-gnu/miniforge3/envs/osl/lib
Headers = /media/ssd/skyhammer/neue/install/aarch64-unknown-linux-gnu/miniforge3/envs/osl/include/qt
